import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:url_launcher/url_launcher.dart';

import 'core/providers/app_state_provider.dart';
import 'core/providers/entries_provider.dart';
import 'core/providers/subscription_provider.dart';
import 'core/providers/theme_provider.dart';
import 'core/services/iap_service.dart';
import 'core/services/local_storage.dart';
import 'core/services/scripture_engine.dart';
import 'core/utils/error_handler.dart';
import 'core/utils/theme.dart';
import 'platform/admob_service.dart';
import 'platform/notification_service.dart';
import 'screens/home_dashboard.dart';
import 'screens/onboarding_screen.dart';
import 'widgets/accessibility_wrapper.dart';

void main() {
  final widgetsBinding = WidgetsFlutterBinding.ensureInitialized();
  // Holds the OS-level splash screen (generated by flutter_native_splash)
  // on screen through the async initialization below, instead of letting
  // it disappear at Flutter's first frame and exposing the separate
  // "Loading GraceLog..." fallback screen.
  FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
  ErrorHandler.setup();
  runApp(const GraceLogApp());
}

/// GraceLog root widget.
class GraceLogApp extends StatefulWidget {
  const GraceLogApp({super.key});

  @override
  State<GraceLogApp> createState() => _GraceLogAppState();
}

class _GraceLogAppState extends State<GraceLogApp> {
  final ThemeProvider _themeProvider = ThemeProvider();
  final SubscriptionProvider _subscriptionProvider = SubscriptionProvider();
  final AppStateProvider _appStateProvider = AppStateProvider();
  final EntriesProvider _entriesProvider = EntriesProvider();

  bool _isInitializing = true;
  bool _hasSeenOnboarding = false;
  String? _initError;

  @override
  void initState() {
    super.initState();
    _initializeApp();
  }

  Future<void> _initializeApp() async {
    try {
      await LocalStorage().database;
      await ScriptureEngine().initialize();
      await IAPService().initialize();
      await AdMobService().initialize();
      await NotificationService().initialize();

      AdMobService().shouldShowAds = () => !_subscriptionProvider.value;

      await _entriesProvider.loadEntries();

      final prefs = await SharedPreferences.getInstance();
      final seenOnboarding = prefs.getBool(OnboardingScreen.prefsKey) ?? false;

      if (mounted) {
        setState(() {
          _hasSeenOnboarding = seenOnboarding;
          _isInitializing = false;
        });
      }
    } catch (e, stackTrace) {
      ErrorHandler.logError(e, stackTrace);
      if (mounted) {
        setState(() {
          _isInitializing = false;
          _initError = 'Failed to initialize app. Please restart.';
        });
      }
    } finally {
      // Removed here, not left to the default first-frame behavior, so
      // the native splash hands off directly to real content.
      FlutterNativeSplash.remove();
    }
  }

  @override
  Widget build(BuildContext context) {
    if (_isInitializing) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Builder(
          builder: (context) => Scaffold(
            backgroundColor: Theme.of(context).scaffoldBackgroundColor,
            body: Center(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                children: [
                  CircularProgressIndicator(color: Theme.of(context).colorScheme.primary),
                  const SizedBox(height: 20),
                  Text('Loading GraceLog...', style: Theme.of(context).textTheme.bodyLarge),
                ],
              ),
            ),
          ),
        ),
      );
    }

    if (_initError != null) {
      return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Builder(
          builder: (context) => Scaffold(
            backgroundColor: Theme.of(context).scaffoldBackgroundColor,
            body: Center(
              child: Padding(
                padding: const EdgeInsets.all(32),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    Icon(Icons.error_outline, size: 48, color: Theme.of(context).colorScheme.error),
                    const SizedBox(height: 16),
                    Text(_initError!, textAlign: TextAlign.center, style: Theme.of(context).textTheme.bodyLarge),
                    const SizedBox(height: 24),
                    ElevatedButton(onPressed: _initializeApp, child: const Text('Retry')),
                  ],
                ),
              ),
            ),
          ),
        ),
      );
    }

    return ListenableBuilder(
      listenable: _themeProvider,
      builder: (context, _) {
        return MaterialApp(
          title: 'GraceLog',
          debugShowCheckedModeBanner: false,
          theme: AppTheme.buildLightTheme(),
          darkTheme: AppTheme.buildDarkTheme(),
          themeMode: _themeProvider.value,
          localizationsDelegates: const [
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          supportedLocales: const [
            Locale('en'), Locale('es'), Locale('fr'), Locale('de'), Locale('pt'),
            Locale('ar'), Locale('hi'), Locale('ja'), Locale('ko'), Locale('zh'), Locale('he'),
          ],
          locale: _appStateProvider.value.currentLocale,
          home: _hasSeenOnboarding ? const HomeDashboard() : const OnboardingScreen(),
          builder: (context, child) {
            ErrorWidget.builder = (details) {
              return Scaffold(
                backgroundColor: Theme.of(context).scaffoldBackgroundColor,
                body: SafeArea(
                  child: Padding(
                    padding: const EdgeInsets.all(24),
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(
                          Icons.broken_image_outlined,
                          size: 48,
                          color: Theme.of(context).colorScheme.onSurface.withOpacity(0.4),
                        ),
                        const SizedBox(height: 16),
                        Text('Something went wrong', style: Theme.of(context).textTheme.headlineSmall),
                        const SizedBox(height: 8),
                        Text(
                          details.exception.toString(),
                          textAlign: TextAlign.center,
                          style: Theme.of(context).textTheme.bodySmall,
                        ),
                        const SizedBox(height: 24),
                        ElevatedButton(onPressed: () => _initializeApp(), child: const Text('Restart App')),
                        const SizedBox(height: 12),
                        TextButton(
                          onPressed: () async {
                            final uri = Uri(
                              scheme: 'mailto',
                              path: 'support@gracelog.app',
                              queryParameters: {
                                'subject': 'GraceLog Error Report',
                                'body': 'Error: ${details.exception}\n\nStack: ${details.stack}',
                              },
                            );
                            if (await canLaunchUrl(uri)) await launchUrl(uri);
                          },
                          child: Text('Report issue: support@gracelog.app', style: Theme.of(context).textTheme.labelSmall),
                        ),
                      ],
                    ),
                  ),
                ),
              );
            };
            return AccessibilityWrapper.interactive(
              label: 'GraceLog app',
              child: child ?? const SizedBox.shrink(),
            );
          },
        );
      },
    );
  }
}
